### ISSUE TITLE
Runnable raises errors from 1.1.2v.

### ISSUE THREAD

**Issue by goliath-yamon** [langflow-ai/langflow#6123]
### Bug Description

I tried upgrading from 1.1.1 to 1.1.2, 1.1.3, and 1.1.4 to resolve the streaming session issue.
My runnable component worked in 1.1.1 and previous versions, but the newer versions caused it to stop working.

I think the place where calls `get_output` method has an error in newer versions.

### Reproduction

1. I just built the flows and got the error below.
  `RunnableExecComponent.get_output() missing 2 required positional arguments: 'input_key' and 'output_key'`

2. I changed the parameters of `get_output` method according to the first error
  ```python
  get_output(self, result, input_key = None, output_key = None):
      if input_key is None:
          input_key = self.input_key
      if output_key is None:
          output_key = self.output_key
      ....
  ``` 
  After that, I got the error below.
  ```
  'str' object has no attribute 'get'
   
  Traceback (most recent call last):
    File "/app/.venv/lib/python3.12/site-packages/langflow/api/v1/chat.py", line 242, in _build_vertex
      vertex_build_result = await graph.build_vertex(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/.venv/lib/python3.12/site-packages/langflow/graph/graph/base.py", line 1440, in build_vertex
      await vertex.build(
    File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 839, in build
      await step(user_id=user_id, event_manager=event_manager, **kwargs)
    File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 485, in _build
      await self._build_each_vertex_in_params_dict()
    File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 576, in _build_each_vertex_in_params_dict
      await self._build_vertex_and_update_params(
    File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 671, in _build_vertex_and_update_params
      result = await vertex.get_result(self, target_handle_name=key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/base.py", line 621, in get_result
      return await self._get_result(requester, target_handle_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/vertex_types.py", line 131, in _get_result
      output = self.get_output(edge.source_handle.name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/app/.venv/lib/python3.12/site-packages/langflow/graph/vertex/vertex_types.py", line 54, in get_output
      return self.custom_component.get_output(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 141, in get_output
  AttributeError: 'str' object has no attribute 'get'
  ``` 

3. I changed the name of `get_output` to other name and got the error below
  `Error building Component Chat Output: "Input to ChatPromptTemplate is missing variables {'system_prompt'}. Expected: ['input', 'system_prompt'] Received: ['input', 'intermediate_steps', 'agent_scratchpad']\nNote: if you intended {system_prompt} to be part of the string and not a variable, please escape it with double curly braces like: '{{system_prompt}}'.\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_PROMPT_INPUT`

### Expected behavior

It should work as previous versions.

### Operating System

Debian GNU/Linux 12 (bookworm)

### Langflow Version

1.1.2, 1.1.3, 1.1.4

### Python Version

3.12

**Comment by YamonBot** [comment]
We urgently need this feature. Please help us.
