### ISSUE TITLE
Voice mode not working on Ubuntu 25.04: Error with API key: 'function' object has no attribute 'send_json'

### ISSUE THREAD

**Issue by GottfriedHofmann** [langflow-ai/langflow#10654]
### Bug Description

When using voice mode in playground on Linux with the python package installation in a virtual environment, I get the following error on the terminal:

2025-11-19T14:12:47.932868Z [error    ] Error with API key: 'function' object has no attribute 'send_json'
2025-11-19T14:12:47.934018Z [error    ] Traceback (most recent call last):
  File "/home/g/LangFlow_312/lib/python3.12/site-packages/langflow/api/v1/voice_mode.py", line 110, in authenticate_and_get_openai_key
    await websocket.send_json(
          ^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'send_json'

2025-11-19T14:12:49.689420Z [error    ] Unexpected error: 'BoundLoggerFilteringAtInfo' object has no attribute 'trace'
2025-11-19T14:12:49.690809Z [error    ] Traceback (most recent call last):
  File "/home/g/LangFlow_312/lib/python3.12/site-packages/langflow/api/v1/voice_mode.py", line 1215, in flow_tts_websocket
    openai_send(tts_realtime_session)
  File "/home/g/LangFlow_312/lib/python3.12/site-packages/langflow/api/v1/voice_mode.py", line 1182, in openai_send
    logger.trace(f"Sending text {LF_TO_OPENAI}: {payload['type']}")
    ^^^^^^^^^^^^
  File "/home/g/LangFlow_312/lib/python3.12/site-packages/structlog/_config.py", line 425, in __getattr__
    return getattr(bl, name)
           ^^^^^^^^^^^^^^^^^
AttributeError: 'BoundLoggerFilteringAtInfo' object has no attribute 'trac

### Reproduction

1. Install langflow as python package in a virtual environment including audio:
uv pip install langflow
uv pip install langflow[audio]
2. Run langflow and select the Simple Agent template
3. Insert your OpenAI key and go to playground
4. Select the mic icon, go to preferences and insert your OpenAI key there as well
5. Try to use the voice mode.
 

### Expected behavior

Chat with the AI using your natural voice.

### Operating System

Ubuntu Linux 25.04

### Langflow Version

1.6.8

### Python Version

3.12

### Flow File

[Simple Agent.json](https://github.com/user-attachments/files/23630025/Simple.Agent.json)

**Comment by AntonioABLima** [comment]
I’m unsure about the current state of the **Voice feature**. I’ve just reached out to the core team to confirm if it’s still **active**, **on hold**, or **deprecated**. I’ll let you know as soon as I get a definitive answer.

**Comment by AntonioABLima** [comment]
I’ve checked with the team, but unfortunately, I wasn't able to get any definitive information regarding the Voice mode status. Are you still facing those issues on your end? Thank you for your patience while I looked into this.
