### ISSUE TITLE
FAISS component seems to be producing a runtime error with 1.1.3

### ISSUE THREAD

**Issue by bsleuth** [langflow-ai/langflow#6072]
```
RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at                 
                             /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open                   
                             /home/xxx/LangFlow/test/index.faiss for reading: No such file or             
                             directory 
```

I would expect the component to create the directory if it does not exist? This does seem like an issue after upgrading from 1.1.1 - don't know whether I am missing something...

I am starting langflow from the LangFlow directory on Ubuntu 24

**Comment by bsleuth** [comment]
@dosu

THe persist directory exists as 'test' and the inde name is provided as 'index'.

If I create the directory manually I get:

RuntimeError: Error in faiss::FileIOReader::FileIOReader(const char*) at                 
                             /project/faiss/faiss/impl/io.cpp:67: Error: 'f' failed: could not open                   
                             /home/xxx/LangFlow/test/index.faiss for reading: No such file or             
                             directory

**Comment by bsleuth** [comment]
I think there is something wrong. Could someone please help?

**Comment by Cristhianzl** [comment]
hi @bsleuth,

The component is failing due to path resolution issues after becoming outdated. Please review PR #6081 for the fix.

![Image](https://github.com/user-attachments/assets/a29598fd-ab4f-4e6e-a27c-f962a6fcce3e)

**Comment by indramal** [comment]
Same issue. File not write that is the issue. File reading is working fine.

**Comment by Cristhianzl** [comment]
@indramal #6081 the fix :)
