### ISSUE TITLE
Database initialization fails after upgrading Langflow from v1.0.19.post2 to v1.1.0 with PostgreSQL

### ISSUE THREAD

**Issue by rwb-truelime** [langflow-ai/langflow#4698]
### Bug Description

After upgrading Langflow from v1.0.19.post2 to v1.1.0 in a Docker setup with PostgreSQL, the application fails to start due to a database initialization error. The error suggests SQLAlchemy is trying to use SQLite dialects despite being configured for PostgreSQL.

### Reproduction

1. Have a working Langflow v1.0.19.post2 setup with PostgreSQL:

docker-compose.yml:
```yaml
services:
  langflow:
    image: langflowai/langflow:v1.0.19.post2
    env_file:
      - .env
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    volumes:
      - ./langflow-data:/app/langflow

  postgres:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - ./langflow-postgres:/var/lib/postgresql/data
```

2. Update the Langflow image to v1.1.0 in docker-compose.yml:
```yaml
services:
  langflow:
    image: langflowai/langflow:v1.1.0
    # rest of config remains the same
```

3. Run `docker-compose up -d`

4. Application fails with error:
```
AttributeError: module 'sqlalchemy.dialects' has no attribute 'sqlite'
```

Full error occurs during database initialization when trying to inspect the database connection:
```python
File "/app/.venv/lib/python3.12/site-packages/langflow/services/database/service.py", line 121, in on_connection
    dbapi_connection, sqlite3.Connection | sa.dialects.sqlite.aiosqlite.AsyncAdapt_aiosqlite_connection
                                          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'sqlalchemy.dialects' has no attribute 'sqlite'
```

### Expected behavior

The upgrade from v1.0.19.post2 to v1.1.0 should maintain database compatibility with PostgreSQL and start normally as it did in the previous version.

### Who can help?

@italojohnny - Backend issue related to database initialization and PostgreSQL compatibility
@ogabr

### Operating System

Operating System: Linux (WSL2) Ubuntu 22.04

### Langflow Version

Langflow Version: Upgrading from v1.0.19.post2 to v1.1.0

### Python Version

3.12

**Comment by moiraphill** [comment]
Same error here!

**Comment by rwb-truelime** [comment]
Thanks for the update @italojohnny , missed that one!

**Comment by azdolinski** [comment]
```text
services:
  langflow:
    image: langflowai/langflow-nightly:latest
```
_[Starting Langflow v1.1.0.dev4]_

confirm that it works well...  👏
