### ISSUE TITLE
Operator HTTPS exemption in provider_ssrf is unreachable when LANGFLOW_SSRF_ALLOWED_HOSTS uses a CIDR range (regression in 1.12.3rc0)

### ISSUE THREAD

**Issue by daniellicnerski1** [langflow-ai/langflow#15261]
### Bug Description

The HTTPS guard introduced in #15208 (`fix(security): Guard provider base_url against SSRF and credential exfiltration`) documents an operator escape hatch:

> The one exception is a host the *operator* explicitly allowlisted via `ssrf_allowed_hosts`: that is a deliberate deployment decision (a plaintext internal gateway on a trusted segment), not something a tenant can arrange.

**That escape hatch is unreachable when the allowlist entry is written as a CIDR range**, which is the documented form of `LANGFLOW_SSRF_ALLOWED_HOSTS` and the form every other consumer of the allowlist honours.

The result is that an operator who has already allowlisted the network gets a hard build failure whose remediation text instructs them to do the thing they have already done:

```
Error building Component OpenAI:

Provider endpoint 'http://172.17.0.3:8080/v1' must use https. The configured provider
credential is sent to this endpoint, and a plaintext connection would transmit it in the
clear. Use an https endpoint, or have an operator allowlist the host via
LANGFLOW_SSRF_ALLOWED_HOSTS if a plaintext internal gateway is intended.
```

…with `LANGFLOW_SSRF_ALLOWED_HOSTS=172.16.0.0/12,10.0.0.0/8,192.168.0.0/16` set on the container, and `172.17.0.3` plainly inside `172.16.0.0/12`.

**This is a regression: it last worked in 1.12.2**, where `_require_https_for_credentialed_endpoint` did not exist.

#### Root cause

`src/lfx/src/lfx/base/models/provider_ssrf.py:111`

```python
if parsed.scheme == "http" and hostname and is_host_allowed(hostname):
    return
```

`is_host_allowed` is called **without the `ip` argument**. In `src/lfx/src/lfx/utils/ssrf_protection.py`, CIDR matching lives entirely inside the `if ip:` block:

```python
def is_host_allowed(hostname: str, ip: str | None = None, allowed_hosts: list[str] | None = None) -> bool:
    ...
    if hostname in allowed_hosts:          # exact host  -> reachable
        return True
    for allowed in allowed_hosts:          # *.wildcard  -> reachable
        ...
    if ip:                                 # <-- never true from provider_ssrf.py:111
        ...
        for allowed in allowed_hosts:
            if "/" in allowed:             # CIDR        -> UNREACHABLE
                network = ipaddress.ip_network(allowed, strict=False)
                if ip_obj in network:
                    return True
    return False
```

So for a base URL whose host is a literal IP, the CIDR half of the allowlist is never evaluated.

Three things indicate this is an oversight rather than intent:

1. `get_allowed_hosts()`'s own docstring advertises the contract as *"allowed hosts **and/or CIDR ranges**"*.
2. Every other call site passes `ip`, so CIDR works everywhere else — `base/knowledge_bases/backends/destination_policy.py:107` (`ip=ip`), and `utils/ssrf_protection.py:324, 362, 975, 1019`.
3. The existing unit tests pin exactly that semantics: `is_host_allowed("example.com", "10.0.0.1") is True` — CIDR matching requires the second argument.

#### Impact

Any deployment that reaches a **self-hosted, plaintext, private-network model endpoint** and allowlists it **by range** stops working on upgrade from 1.12.2 to 1.12.3. The component fails at build time, so no flow using it runs at all.

Reached through 13 component modules across 8 provider families — OpenAI / OpenAI Chat Model, Anthropic, Groq, AIML, Mistral Embeddings, IBM WatsonX (+ embeddings), NVIDIA (chat / embedding / ingest / rerank), SambaNova and vLLM — via `openai_compatible_client_kwargs`, `provider_httpx_clients`, `provider_httpx_client_kwargs` and `validate_provider_base_url`.

Provider default endpoints are unaffected (`_is_provider_default` filters them before the guard), so this is scoped to tenant-supplied base URLs — i.e. precisely the self-hosted / on-prem population.

#### Secondary finding: the two allowlists have incompatible grammars

`LANGFLOW_SSRF_ALLOWED_HOSTS` accepts a host, a `*.domain` wildcard and a CIDR, but **not** a scheme prefix and not `host:port` (`get_allowed_hosts` only splits on `,` and strips).

`LANGFLOW_PROVIDER_CREDENTIAL_ALLOWED_HOSTS` accepts a host, `host:port`, a `*.domain` wildcard and an optional `http://` prefix to opt into cleartext, but **not** a CIDR.

An operator who mirrors the `http://host` syntax they learned from the second variable into the first also gets no effect, silently.

### Reproduction

Two runs of the same flow against the same Langflow version and the same endpoint. The only variable is how the allowlist entry is written.

**1. Start a plaintext HTTP endpoint on a private address**

```bash
docker run -d --name echo-repro ghcr.io/mccutchen/go-httpbin
ECHO_IP=$(docker inspect -f '{{.NetworkSettings.Networks.bridge.IPAddress}}' echo-repro)
echo "$ECHO_IP"   # e.g. 172.17.0.3, inside 172.16.0.0/12
```

**2. Start Langflow 1.12.3rc0 with the network allowlisted by RANGE**

```bash
docker run -d --name langflow-repro -p 7860:7860 \
  -e LANGFLOW_AUTO_LOGIN=true \
  -e LANGFLOW_SSRF_ALLOWED_HOSTS="172.16.0.0/12,10.0.0.0/8,192.168.0.0/16" \
  langflowai/langflow:1.12.3rc0
```

Confirm the endpoint is reachable from inside the Langflow container, so nothing below is a network problem:

```bash
docker exec langflow-repro curl -s -o /dev/null -w '%{http_code}\n' "http://$ECHO_IP:8080/v1/chat/completions"
# 404
```

**3. Build a flow**: `Chat Input` -> `OpenAI` -> `Chat Output`. On the OpenAI component set

- `OpenAI API Base` = `http://<ECHO_IP>:8080/v1`
- `OpenAI API Key` = `sk-test` (the guard fires before any request, so the key need not be valid)

Run it from the Playground.

**Actual result** — the run fails and the endpoint is never contacted:

```
Provider endpoint 'http://172.17.0.3:8080/v1' must use https. The configured provider
credential is sent to this endpoint, and a plaintext connection would transmit it in the
clear. Use an https endpoint, or have an operator allowlist the host via
LANGFLOW_SSRF_ALLOWED_HOSTS if a plaintext internal gateway is intended.
```

**4. Restart the identical image, changing only the FORM of the allowlist entry**

```bash
docker rm -f langflow-repro
docker run -d --name langflow-repro -p 7860:7860 \
  -e LANGFLOW_AUTO_LOGIN=true \
  -e LANGFLOW_SSRF_ALLOWED_HOSTS="172.17.0.3" \
  langflowai/langflow:1.12.3rc0
```

Run the same flow with the same base URL.

**Actual result** — the HTTPS refusal is gone and the request reaches the endpoint:

```
404 page not found
```

`404 page not found` is go-httpbin's own response body, i.e. the request left Langflow, crossed the network and came back.

**5. Control — the same range-based allowlist on 1.12.2**

```bash
docker run -d --name langflow-1122 -p 7861:7860 \
  -e LANGFLOW_AUTO_LOGIN=true \
  -e LANGFLOW_SSRF_ALLOWED_HOSTS="172.16.0.0/12,10.0.0.0/8,192.168.0.0/16" \
  langflowai/langflow:1.12.2
```

Build the same flow there and run it with the same base URL. It reaches the endpoint and
returns `404 page not found`. There is no HTTPS refusal.

(Build the flow fresh on the 1.12.2 instance rather than exporting it from 1.12.3 and
importing: an exported flow embeds the component's source, and 1.12.3's OpenAI component
imports `ensure_credential_endpoint_allowed`, which does not exist in 1.12.2 — the import
fails with `ImportError: Cannot import name 'ensure_credential_endpoint_allowed' from
'lfx.base.models.provider_ssrf'`.)

### Expected behavior

A `LANGFLOW_SSRF_ALLOWED_HOSTS` entry whose CIDR range covers the endpoint's host should satisfy the operator exemption in `_require_https_for_credentialed_endpoint`, exactly as it does for every other consumer of the allowlist and as `get_allowed_hosts()`'s documented contract states.

A minimal fix is to give `is_host_allowed` the IP it needs when the hostname is already an IP literal:

```python
# src/lfx/src/lfx/base/models/provider_ssrf.py
ip_literal = None
with contextlib.suppress(ValueError):
    ip_literal = str(ipaddress.ip_address(hostname))

if parsed.scheme == "http" and hostname and is_host_allowed(hostname, ip=ip_literal):
    return
```

If instead the intent is that **only** an exact host or wildcard may opt a plaintext endpoint out of the HTTPS requirement — with CIDR ranges deliberately not being sufficient — then the error message should say so, because as written it points the operator at a remedy that cannot work for them, and the change should be called out in the release notes as breaking for range-based allowlists.

### Who can help?

@erichare (author of #15208)

### Operating System

macOS 15 (Darwin 25.6.0), arm64 — Docker via colima. Reproduced identically on `ubuntu-latest` GitHub Actions runners.

### Langflow Version

1.12.3rc0 (regression — last worked in 1.12.2)

### Python Version

3.14 (as shipped in the `langflowai/langflow:1.12.3rc0` image)
