### ISSUE TITLE
MCP Server Fails to Start in Langflow

### ISSUE THREAD

**Issue by dambor** [langflow-ai/langflow#10019]
Unable to start the MCP server on Langflow. The application displays an unexpected error message instead of starting successfully.

## Error Message
```
Sorry, we found an unexpected error!
Please report errors with detailed tracebacks on the GitHub Issues page.
Thank you!
```

## Steps to Reproduce
1. Open a flow
2. Try to initialize/start the MCP server
3. Error screen appears with the message above

## Environment
- **Langflow Version**: 1.6.0
- **Operating System**: macOS 14
- **Installation Method**: source

## Logs/Tracebacks
```
hook.js:608 TypeError: v.map is not a function
    at Ji1 (index-DxJbNhsQ.js:14986:27291)
    at c0n (index-DxJbNhsQ.js:1017:17270)
    at dnn (index-DxJbNhsQ.js:1019:3181)
    at bMr (index-DxJbNhsQ.js:1019:45438)
    at pMr (index-DxJbNhsQ.js:1019:40301)
    at xeo (index-DxJbNhsQ.js:1019:40224)
    at C4t (index-DxJbNhsQ.js:1019:40071)
    at wnn (index-DxJbNhsQ.js:1019:36361)
    at Str (index-DxJbNhsQ.js:1019:37176)
    at $$ (index-DxJbNhsQ.js:1017:3347)
    at index-DxJbNhsQ.js:1019:34654
```

---

**Note**: Please fill in the bracketed sections with your specific information before submitting.

**Comment by Empreiteiro** [comment]
@dambor Are you using any specific environment parameters?

The error occurs when you try to add a specific MCP or immediately after clicking "add mcp server."?

**Comment by akshays548** [comment]
@dambor  we are also facing some issues for MCP server while trying to host the created flows under a project.
[issue 10172: MCP Server tab fails to load with separate frontend pod deployment in Kubernetes ](https://github.com/langflow-ai/langflow/issues/10172 )
Are you facing the same issue or its different ?
@Empreiteiro

**Comment by dambor** [comment]
The issue was more rudimentar. I was just trying to open the MCP tab and was getting that error.
Nevertheless, the problem is fixed after upgrading to 1.6.4. I will go ahead and close the ticket.
Thanks
